//This file is autogenerated. All manuel changes will be lost.
using System;
using System.Diagnostics;
using System.Linq;
using System.Net.NetworkInformation;

namespace YonderSharp.CopyProtection
{
    public partial class CopyProtection{
        /// <summary>
        /// Gets the date of the last compilation.
        /// Auto generated via T4
        /// </summary>
        public static DateTime GetCompileDate(){
            return new DateTime(2024, 8, 21);
        }
    }
}